# Site settings
title: "Gozzip Blog"
description: "A modern blog covering trending topics, culture, and interesting discussions from around the web"
baseurl: "/gozzip" # the subpath of your site, e.g. /blog
url: "https://oujii.github.io" # the base hostname & protocol for your site
author: "Gozzip"
email: "contact@gozzip.com"

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# GitHub Pages compatibility
safe: true
source: .
destination: ./_site
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default front matter
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Gozzip"
      comments: true
      show_date: true
      show_author: true
      show_categories: true
      show_tags: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "_pages"
      type: "pages"
    values:
      layout: "page"

# Pagination
paginate: 10
paginate_path: "/page:num/"

# Social links
social:
  twitter: gozzip_blog
  github: gozzip
  linkedin: gozzip

# Navigation
navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Archive"
    url: "/archive/"
  - title: "Categories"
    url: "/categories/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CHANGELOG.md

# Include
include:
  - _pages

# Timezone
timezone: UTC

# Permalink structure
permalink: /:categories/:year/:month/:day/:title/

# SEO settings
lang: en_US
locale: en_US

# Feed settings
feed:
  posts_limit: 20
  excerpt_only: false

# Comments (can be enabled later with services like Disqus)
comments:
  provider: false

# Analytics (can be configured later)
analytics:
  provider: false
